FILENAME THEJUNOD "data.xml";
FILENAME map "map.xml";
LIBNAME THEJUNOD xml xmlmap=map access=readonly;
PROC DATASETS LIBRARY=THEJUNOD;
COPY OUT=work; RUN; PROC FORMAT;

VALUE CL_1_
	1="Yes"
	2="No";
VALUE $CL_5_
	"1"="First Visit"
	"3"="3-week Follow Up"
	"6"="6-week Follow Up"
	"10"="Subsequent Follow Up Visits"
	"99"="Logs";
VALUE CL_9_
	1="Yes"
	0="No";
VALUE CL_12_
	1="Male"
	2="Female";
VALUE CL_13_
	1="Hispanic"
	2="Non Hispanic"
	3="Unknown";
VALUE CL_15_
	1="Single"
	2="Married"
	3="Divorced/Separated"
	4="Widowed"
	5="Unknown";
VALUE CL_16_
	1="Did not graduate from High School"
	2="High School or GED"
	3="2 year college"
	4="4 year college"
	5="Masters"
	6="PhD";
VALUE $CL_18_
	"Y"="Yes"
	"N"="No";
VALUE CL_70_
	0="Negative"
	9="Trace"
	1="1+"
	2="2+"
	3="3+"
	4="4+";
VALUE CL_71_
	1="Positive"
	0="Negative";
VALUE CL_20_
	0="Negative"
	9="Trace"
	1="1+"
	2="2+"
	3="3+"
	4="4+";
VALUE CL_21_
	1="Positive"
	0="Negative";
VALUE CL_23_
	1="Celsius"
	2="Fahrenheit";
VALUE CL_24_
	1="lbs/inches"
	2="cm/kg";
VALUE CL_25_
	1="Yes"
	2="No";
VALUE CL_30_
	1="Yes"
	2="No"
	3="N/A";
VALUE CL_32_
	1="Normal"
	2="Abnormal";
VALUE CL_34_
	1="Yes"
	2="No";
VALUE CL_36_
	1="Eligible"
	2="Ineligible";
VALUE CL_39_
	1="Normal"
	2="Abnormal"
	99="Not Examined";
VALUE CL_40_
	1="Normal"
	2="Abnormal";
VALUE CL_42_
	1="I"
	2="II"
	3="III"
	4="IV"
	5="V";
VALUE CL_43_
	1="None"
	2="Dose Interrupted"
	3="Dose Discontinued"
	4="Dose Modified";
VALUE CL_44_
	1="Recovered without sequelae"
	2="Recovered with sequelae"
	3="Ongoing"
	4="Unknown"
	5="Other";
VALUE CL_45_
	1="Yes"
	2="No";
VALUE CL_47_
	1="Hourly"
	2="Daily"
	3="2x per day"
	4="3x per day"
	5="Weekly"
	6="Monthly"
	7="As needed";
VALUE CL_48_
	1="Yes"
	2="No";
VALUE CL_49_
	1="Death"
	2="Life-threatening"
	3="Prolonged hospitalization"
	4="Disability"
	5="Other";
VALUE CL_51_
	1="First Visit"
	2="1-week Follow Up"
	3="2-week Follow Up"
	4="Monthly Follow Up";
VALUE CL_52_
	1="Inclusion/Exclusion"
	2="Neurological Exam"
	3="MRI"
	4="Pharmacokinetics"
	5="Vital Signs"
	6="Local Lab"
	7="Physical Exam";
VALUE CL_56_
	1="Mother"
	2="Father"
	3="Brother"
	4="Sister"
	5="Maternal Grandfather"
	6="Maternal Grandmother"
	7="Maternal Aunt"
	8="Paternal Grandfather"
	10="Paternal Grandmother"
	11="Paternal Uncle"
	12="Paternal Aunt";
VALUE CL_57_
	1="Yes"
	0="No";
VALUE CL_58_
	0="None"
	1="1"
	2="2"
	3="3"
	4="4"
	5="5"
	6="6 or more";
VALUE CL_59_
	0="0-1 day/week"
	2="2-3 days/week"
	4="4-5 days/week"
	6="6-7 days/week";
VALUE CL_60_
	0="0-1 day/week"
	2="2-3 days/week"
	4="4-5 days/week"
	6="6-7 days/week";
VALUE CL_64_
	1="Morning"
	2="Mid-day"
	3="Afternoon"
	4="Evening";
VALUE CL_66_
	1="Light"
	2="Moderate"
	3="Vigorous";
VALUE CL_67_
	0="Never"
	1="Rarely"
	2="Sometimes"
	3="Often"
	4="Always";
VALUE CL_74_
	1="Option 1: Ear,Nose,Throat"
	2="Option 2: Eyes"
	3="Option 3: Carniofacial";
VALUE CL_77_
	1="Ear,Nose,Throat"
	2="Eyes"
	3="Craniofacial"
	4="Other";
VALUE CL_80_
	1="Yes"
	2="No";
VALUE CL_84_
	1="Completed"
	2="In Progess"
	3="On Hold"
	4="Not Completed";
RUN;


DATA IG_COMPL_CD;
SET IG_COMPL_CD;
FORMAT CD_YN CL_1_.; RUN;

DATA IG_COMPL_CD;
SET IG_COMPL_CD;
FORMAT MISS_EV CL_5_.; RUN;

DATA IG_VERIF_VERIFY;
SET IG_VERIF_VERIFY;
FORMAT ELIGI001 CL_9_.; RUN;

DATA IG_DEMOG_DEMO;
SET IG_DEMOG_DEMO;
FORMAT DEM_GEN CL_12_.; RUN;

DATA IG_DEMOG_DEMO;
SET IG_DEMOG_DEMO;
FORMAT DEM_ETH CL_13_.; RUN;

DATA IG_DEMOG_DEMO;
SET IG_DEMOG_DEMO;
FORMAT DEM_MAR CL_15_.; RUN;

DATA IG_DEMOG_DEMO;
SET IG_DEMOG_DEMO;
FORMAT DEM_EDU CL_16_.; RUN;

DATA IG_DIABE_DIABETES;
SET IG_DIABE_DIABETES;
FORMAT DIABE003 CL_18_.; RUN;

DATA IG_DIABE_DIABETES;
SET IG_DIABE_DIABETES;
FORMAT INSULIN_ CL_18_.; RUN;

DATA IG_DIABE_DIABETES;
SET IG_DIABE_DIABETES;
FORMAT RETINOPA CL_18_.; RUN;

DATA IG_DIABE_DIABETES;
SET IG_DIABE_DIABETES;
FORMAT SGOCCUR CL_18_.; RUN;

DATA IG_DIABE_DIABETES;
SET IG_DIABE_DIABETES;
FORMAT AUTONOMI CL_18_.; RUN;

DATA IG_DIABE_DIABETES;
SET IG_DIABE_DIABETES;
FORMAT OTHER_DI CL_18_.; RUN;

DATA IG_DIABE_DIABETES;
SET IG_DIABE_DIABETES;
FORMAT DIABETIC CL_18_.; RUN;

DATA IG_DIABE_DIABETES;
SET IG_DIABE_DIABETES;
FORMAT SEVERE_H CL_18_.; RUN;

DATA IG_LOCAL_TESTS;
SET IG_LOCAL_TESTS;
FORMAT UR_PRO CL_70_.; RUN;

DATA IG_LOCAL_TESTS;
SET IG_LOCAL_TESTS;
FORMAT UR_LEUK CL_71_.; RUN;

DATA IG_LOCAL_TESTS;
SET IG_LOCAL_TESTS;
FORMAT UR_NITR CL_71_.; RUN;

DATA IG_VITAL_VITALS;
SET IG_VITAL_VITALS;
FORMAT VS_TUNIT CL_23_.; RUN;

DATA IG_VITAL_VITALS;
SET IG_VITAL_VITALS;
FORMAT VS_UNITS CL_24_.; RUN;

DATA IG_VITAL_VITALS;
SET IG_VITAL_VITALS;
FORMAT VS_BPHR CL_25_.; RUN;

DATA IG_MRI_MRI;
SET IG_MRI_MRI;
FORMAT MRI_YN CL_30_.; RUN;

DATA IG_MRI_MRI;
SET IG_MRI_MRI;
FORMAT MRI_RES CL_32_.; RUN;

DATA IG_INCLU_ELIGIBILITY;
SET IG_INCLU_ELIGIBILITY;
FORMAT IN_18YO CL_34_.; RUN;

DATA IG_INCLU_ELIGIBILITY;
SET IG_INCLU_ELIGIBILITY;
FORMAT IN_T2MEL CL_34_.; RUN;

DATA IG_INCLU_ELIGIBILITY;
SET IG_INCLU_ELIGIBILITY;
FORMAT IN_FPLGL CL_34_.; RUN;

DATA IG_INCLU_ELIGIBILITY;
SET IG_INCLU_ELIGIBILITY;
FORMAT IN_HEAC1 CL_34_.; RUN;

DATA IG_INCLU_ELIGIBILITY;
SET IG_INCLU_ELIGIBILITY;
FORMAT IN_FLENG CL_34_.; RUN;

DATA IG_INCLU_ELIGIBILITY;
SET IG_INCLU_ELIGIBILITY;
FORMAT IN_CMSSR CL_34_.; RUN;

DATA IG_INCLU_ELIGIBILITY;
SET IG_INCLU_ELIGIBILITY;
FORMAT IN_IC CL_34_.; RUN;

DATA IG_INCLU_ELIGIBILITY;
SET IG_INCLU_ELIGIBILITY;
FORMAT EX_OGTT CL_34_.; RUN;

DATA IG_INCLU_ELIGIBILITY;
SET IG_INCLU_ELIGIBILITY;
FORMAT EX_RECNT CL_34_.; RUN;

DATA IG_INCLU_ELIGIBILITY;
SET IG_INCLU_ELIGIBILITY;
FORMAT EX_HEP CL_34_.; RUN;

DATA IG_INCLU_ELIGIBILITY;
SET IG_INCLU_ELIGIBILITY;
FORMAT EX_EVINF CL_34_.; RUN;

DATA IG_INCLU_ELIGIBILITY;
SET IG_INCLU_ELIGIBILITY;
FORMAT EX_STRKE CL_34_.; RUN;

DATA IG_INCLU_ELIGIBILITY;
SET IG_INCLU_ELIGIBILITY;
FORMAT EX_PREG CL_34_.; RUN;

DATA IG_INCLU_ELIGIBILITY;
SET IG_INCLU_ELIGIBILITY;
FORMAT EX_MENTL CL_34_.; RUN;

DATA IG_INCLU_ELIGIBILITY;
SET IG_INCLU_ELIGIBILITY;
FORMAT INEX_ELI CL_36_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT APPEARAN CL_39_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT SKIN CL_39_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT HEENT CL_39_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT THYROID CL_39_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT CHEST CL_39_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT LUNGS CL_39_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT BREAST CL_39_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT HEART CL_39_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT ABDOMEN CL_39_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT MUSCULOS CL_39_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT GENITALI CL_39_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT PELVIS CL_39_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT RECTAL CL_39_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT PROSTATE CL_39_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT VASCULAR CL_39_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT NEUROLOG CL_39_.; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT LYMPHNOD CL_39_.; RUN;

DATA IG_PHYSI_OTHERBODYSYSTEMSITE;
SET IG_PHYSI_OTHERBODYSYSTEMSITE;
FORMAT OTHER00i CL_40_.; RUN;

DATA IG_ADVER_AELOG;
SET IG_ADVER_AELOG;
FORMAT AE_SEV CL_42_.; RUN;

DATA IG_ADVER_AELOG;
SET IG_ADVER_AELOG;
FORMAT AE_ACT CL_43_.; RUN;

DATA IG_ADVER_AELOG;
SET IG_ADVER_AELOG;
FORMAT AE_OUT CL_44_.; RUN;

DATA IG_CONCO_CONMEDS;
SET IG_CONCO_CONMEDS;
FORMAT CM_YN CL_45_.; RUN;

DATA IG_CONCO_CONMEDLOG;
SET IG_CONCO_CONMEDLOG;
FORMAT CM_FREQ CL_47_.; RUN;

DATA IG_CONCO_CONMEDLOG;
SET IG_CONCO_CONMEDLOG;
FORMAT CM_ONGNG CL_45_.; RUN;

DATA IG_SERIO_SAE1;
SET IG_SERIO_SAE1;
FORMAT SAE1_YN CL_48_.; RUN;

DATA IG_SERIO_SAE1;
SET IG_SERIO_SAE1;
FORMAT SAE1_CAT CL_49_.; RUN;

DATA IG_SERIO_SAE1;
SET IG_SERIO_SAE1;
FORMAT SAE1_CON CL_48_.; RUN;

DATA IG_SERIO_SAE1;
SET IG_SERIO_SAE1;
FORMAT SAE1_STA CL_48_.; RUN;

DATA IG_SERIO_SAE1;
SET IG_SERIO_SAE1;
FORMAT SAE2_YN CL_48_.; RUN;

DATA IG_SERIO_SAE2;
SET IG_SERIO_SAE2;
FORMAT SAE2_CAT CL_49_.; RUN;

DATA IG_SERIO_SAE2;
SET IG_SERIO_SAE2;
FORMAT SAE2_CON CL_48_.; RUN;

DATA IG_SERIO_SAE2;
SET IG_SERIO_SAE2;
FORMAT SAE2_STA CL_48_.; RUN;

DATA IG_SERIO_SAE2;
SET IG_SERIO_SAE2;
FORMAT SAE3_YN CL_48_.; RUN;

DATA IG_SERIO_SAE3;
SET IG_SERIO_SAE3;
FORMAT SAE3_CAT CL_49_.; RUN;

DATA IG_SERIO_SAE3;
SET IG_SERIO_SAE3;
FORMAT SAE3_CON CL_48_.; RUN;

DATA IG_SERIO_SAE3;
SET IG_SERIO_SAE3;
FORMAT SAE3_STA CL_48_.; RUN;

DATA IG_SERIO_SAE3;
SET IG_SERIO_SAE3;
FORMAT SAE4_YN CL_48_.; RUN;

DATA IG_SERIO_SAE4;
SET IG_SERIO_SAE4;
FORMAT SAE4_CAT CL_49_.; RUN;

DATA IG_SERIO_SAE4;
SET IG_SERIO_SAE4;
FORMAT SAE4_CON CL_48_.; RUN;

DATA IG_SERIO_SAE4;
SET IG_SERIO_SAE4;
FORMAT SAE4_STA CL_48_.; RUN;

DATA IG_SERIO_SAE4;
SET IG_SERIO_SAE4;
FORMAT SAE5_YN CL_48_.; RUN;

DATA IG_SERIO_SAE5;
SET IG_SERIO_SAE5;
FORMAT SAE5_CAT CL_49_.; RUN;

DATA IG_SERIO_SAE5;
SET IG_SERIO_SAE5;
FORMAT SAE5_CON CL_48_.; RUN;

DATA IG_SERIO_SAE5;
SET IG_SERIO_SAE5;
FORMAT SAE5_STA CL_48_.; RUN;

DATA IG_PROTO_PROTOCOLDEVIATIONLOG;
SET IG_PROTO_PROTOCOLDEVIATIONLOG;
FORMAT PD_EVENT CL_51_.; RUN;

DATA IG_PROTO_PROTOCOLDEVIATIONLOG;
SET IG_PROTO_PROTOCOLDEVIATIONLOG;
FORMAT PD_PRODE CL_52_.; RUN;

DATA IG_MEDIC_G2;
SET IG_MEDIC_G2;
FORMAT FAM_ID CL_56_.; RUN;

DATA IG_EATIN_HABITS;
SET IG_EATIN_HABITS;
FORMAT LVALONE CL_57_.; RUN;

DATA IG_EATIN_HABITS;
SET IG_EATIN_HABITS;
FORMAT ADULT CL_58_.; RUN;

DATA IG_EATIN_HABITS;
SET IG_EATIN_HABITS;
FORMAT CHILDREN CL_58_.; RUN;

DATA IG_EATIN_HABITS;
SET IG_EATIN_HABITS;
FORMAT DINNER CL_59_.; RUN;

DATA IG_EATIN_HABITS;
SET IG_EATIN_HABITS;
FORMAT DAIRY CL_60_.; RUN;

DATA IG_EATIN_HABITS;
SET IG_EATIN_HABITS;
FORMAT FRUITS CL_60_.; RUN;

DATA IG_EATIN_HABITS;
SET IG_EATIN_HABITS;
FORMAT VEGGIE CL_60_.; RUN;

DATA IG_EATIN_HABITS;
SET IG_EATIN_HABITS;
FORMAT MEAT CL_60_.; RUN;

DATA IG_EATIN_HABITS;
SET IG_EATIN_HABITS;
FORMAT SWEETS CL_60_.; RUN;

DATA IG_EATIN_HABITS;
SET IG_EATIN_HABITS;
FORMAT VITSUPP CL_57_.; RUN;

DATA IG_PHYSI_PHYSICAL;
SET IG_PHYSI_PHYSICAL;
FORMAT PETIME CL_64_.; RUN;

DATA IG_PHYSI_PHYSICAL;
SET IG_PHYSI_PHYSICAL;
FORMAT PEINTENS CL_66_.; RUN;

DATA IG_PROMI_PROMIS;
SET IG_PROMI_PROMIS;
FORMAT FATEXP20 CL_67_.; RUN;

DATA IG_PROMI_PROMIS;
SET IG_PROMI_PROMIS;
FORMAT FATEXP5 CL_67_.; RUN;

DATA IG_PROMI_PROMIS;
SET IG_PROMI_PROMIS;
FORMAT FATEXP18 CL_67_.; RUN;

DATA IG_PROMI_PROMIS;
SET IG_PROMI_PROMIS;
FORMAT FATEXP33 CL_67_.; RUN;

DATA IG_PROMI_PROMIS;
SET IG_PROMI_PROMIS;
FORMAT FATEXP30 CL_67_.; RUN;

DATA IG_PROMI_PROMIS;
SET IG_PROMI_PROMIS;
FORMAT FATEXP21 CL_67_.; RUN;

DATA IG_PROMI_PROMIS;
SET IG_PROMI_PROMIS;
FORMAT FATEXP40 CL_67_.; RUN;

DATA IG_KITCH_RESPONSEOPTIONS;
SET IG_KITCH_RESPONSEOPTIONS;
FORMAT RES3SS CL_74_.; RUN;

DATA IG_KITCH_RESPONSEOPTIONS;
SET IG_KITCH_RESPONSEOPTIONS;
FORMAT RES6RD CL_77_.; RUN;

DATA IG_KITCH_ITEMOPTIONS;
SET IG_KITCH_ITEMOPTIONS;
FORMAT ITM1NR CL_80_.; RUN;

DATA IG_KITCH_ITEMOPTIONS;
SET IG_KITCH_ITEMOPTIONS;
FORMAT ITM2REQ CL_80_.; RUN;

DATA IG_KITCH_ITEMOPTIONS;
SET IG_KITCH_ITEMOPTIONS;
FORMAT ITM3SHOW CL_80_.; RUN;

DATA IG_KITCH_ITEMOPTIONS;
SET IG_KITCH_ITEMOPTIONS;
FORMAT ITM5SHOW CL_80_.; RUN;

DATA IG_KITCH_DISCREPANCYNOTE;
SET IG_KITCH_DISCREPANCYNOTE;
FORMAT DN1EXAM CL_84_.; RUN;

DATA IG_KITCH_SHOWACTION;
SET IG_KITCH_SHOWACTION;
FORMAT SI1BPHR CL_80_.; RUN;

DATA IG_KITCH_EMAILACTION;
SET IG_KITCH_EMAILACTION;
FORMAT EML1SMT CL_80_.; RUN;